import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/styles/Nav.css"
import Nav from "@/components/Nav";
const { version } = require('.././package.json');

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Katie Hawkes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" version-next-js-package={version}>
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
